package emu.grasscutter.game.scenescript.types.constants;

import org.luaj.vm2.LuaBoolean;
import org.luaj.vm2.LuaTable;
import org.luaj.vm2.LuaValue;
import org.luaj.vm2.lib.TwoArgFunction;

public class OpenState {
	public static class OpenStateCondType extends TwoArgFunction {
		public static final int OPEN_STATE_COND_NONE = 0;
		public static final int OPEN_STATE_COND_PLAYER_LEVEL = 1;
		public static final int OPEN_STATE_COND_QUEST = 2;
		public static final int OPEN_STATE_COND_PARENT_QUEST = 3;

		public LuaValue call(LuaValue modname, LuaValue env) {
			LuaTable scriptConstOpenState = new LuaTable();
			scriptConstOpenState.set("OPEN_STATE_COND_NONE", LuaValue.valueOf(OPEN_STATE_COND_NONE));
			scriptConstOpenState.set("OPEN_STATE_COND_PLAYER_LEVEL", LuaValue.valueOf(OPEN_STATE_COND_PLAYER_LEVEL));
			scriptConstOpenState.set("OPEN_STATE_COND_QUEST", LuaValue.valueOf(OPEN_STATE_COND_QUEST));
			scriptConstOpenState.set("OPEN_STATE_COND_PARENT_QUEST", LuaValue.valueOf(OPEN_STATE_COND_PARENT_QUEST));
			env.set("OpenStateCondType", scriptConstOpenState);
			env.get("package").get("loaded").set("OpenStateCondType", scriptConstOpenState);
			return env;
		}
	}
	public static class OpenStateType extends TwoArgFunction {
		public static final int OPEN_STATE_NONE = 0;
		public static final int OPEN_STATE_PAIMON = 1;
		public static final int OPEN_STATE_PAIMON_NAVIGATION = 2;
		public static final int OPEN_STATE_AVATAR_PROMOTE = 3;
		public static final int OPEN_STATE_AVATAR_TALENT = 4;
		public static final int OPEN_STATE_WEAPON_PROMOTE = 5;
		public static final int OPEN_STATE_WEAPON_AWAKEN = 6;
		public static final int OPEN_STATE_QUEST_REMIND = 7;
		public static final int OPEN_STATE_GAME_GUIDE = 8;
		public static final int OPEN_STATE_COOK = 9;
		public static final int OPEN_STATE_WEAPON_UPGRADE = 10;
		public static final int OPEN_STATE_RELIQUARY_UPGRADE = 11;
		public static final int OPEN_STATE_RELIQUARY_PROMOTE = 12;
		public static final int OPEN_STATE_WEAPON_PROMOTE_GUIDE = 13;
		public static final int OPEN_STATE_WEAPON_CHANGE_GUIDE = 14;
		public static final int OPEN_STATE_PLAYER_LVUP_GUIDE = 15;
		public static final int OPEN_STATE_FRESHMAN_GUIDE = 16;
		public static final int OPEN_STATE_SKIP_FRESHMAN_GUIDE = 17;
		public static final int OPEN_STATE_GUIDE_MOVE_CAMERA = 18;
		public static final int OPEN_STATE_GUIDE_SCALE_CAMERA = 19;
		public static final int OPEN_STATE_GUIDE_KEYBOARD = 20;
		public static final int OPEN_STATE_GUIDE_MOVE = 21;
		public static final int OPEN_STATE_GUIDE_JUMP = 22;
		public static final int OPEN_STATE_GUIDE_SPRINT = 23;
		public static final int OPEN_STATE_GUIDE_MAP = 24;
		public static final int OPEN_STATE_GUIDE_ATTACK = 25;
		public static final int OPEN_STATE_GUIDE_FLY = 26;
		public static final int OPEN_STATE_GUIDE_TALENT = 27;
		public static final int OPEN_STATE_GUIDE_RELIC = 28;
		public static final int OPEN_STATE_GUIDE_RELIC_PROM = 29;
		public static final int OPEN_STATE_COMBINE = 30;
		public static final int OPEN_STATE_GACHA = 31;
		public static final int OPEN_STATE_GUIDE_GACHA = 32;
		public static final int OPEN_STATE_GUIDE_TEAM = 33;
		public static final int OPEN_STATE_GUIDE_PROUD = 34;
		public static final int OPEN_STATE_GUIDE_AVATAR_PROMOTE = 35;
		public static final int OPEN_STATE_GUIDE_ADVENTURE_CARD = 36;
		public static final int OPEN_STATE_FORGE = 37;
		public static final int OPEN_STATE_GUIDE_BAG = 38;
		public static final int OPEN_STATE_EXPEDITION = 39;
		public static final int OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK = 40;
		public static final int OPEN_STATE_GUIDE_ADVENTURE_DUNGEON = 41;
		public static final int OPEN_STATE_TOWER = 42;
		public static final int OPEN_STATE_WORLD_STAMINA = 43;
		public static final int OPEN_STATE_TOWER_FIRST_ENTER = 44;
		public static final int OPEN_STATE_RESIN = 45;
		public static final int OPEN_STATE_WORLD_RESIN = 46;
		public static final int OPEN_STATE_LIMIT_REGION_FRESHMEAT = 47;
		public static final int OPEN_STATE_LIMIT_REGION_GLOBAL = 48;
		public static final int OPEN_STATE_MULTIPLAYER = 49;
		public static final int OPEN_STATE_GUIDE_MOUSEPC = 50;
		public static final int OPEN_STATE_GUIDE_MULTIPLAYER = 51;
		public static final int OPEN_STATE_GUIDE_DUNGEONREWARD = 52;
		public static final int OPEN_STATE_SHOP_TYPE_PAIMON = 1001;
		public static final int OPEN_STATE_SHOP_TYPE_CITY = 1002;
		public static final int OPEN_STATE_SHOP_TYPE_BLACKSMITH = 1003;
		public static final int OPEN_STATE_SHOP_TYPE_GROCERY = 1004;
		public static final int OPEN_STATE_SHOP_TYPE_FOOD = 1005;
		public static final int OPEN_STATE_SHOP_TYPE_SEA_LAMP = 1006;
		public static final int OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP = 1007;
		public static final int OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY = 1008;
		public static final int OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR = 1009;
		public static final int OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT = 1010;
		public static final int OPEN_ADVENTURE_MANUAL = 1100;
		public static final int OPEN_ADVENTURE_MANUAL_CITY_MENGDE = 1101;
		public static final int OPEN_ADVENTURE_MANUAL_CITY_LIYUE = 1102;
		public static final int OPEN_ADVENTURE_MANUAL_MONSTER = 1103;
		public static final int OPEN_STATE_ACTIVITY_SEALAMP = 1200;
		public static final int OPEN_STATE_ACTIVITY_SEALAMP_TAB2 = 1201;
		public static final int OPEN_STATE_ACTIVITY_SEALAMP_TAB3 = 1202;

		public LuaValue call(LuaValue modname, LuaValue env) {
			LuaTable scriptConstOpenState = new LuaTable();
			scriptConstOpenState.set("OPEN_STATE_NONE", LuaValue.valueOf(OPEN_STATE_NONE));
			scriptConstOpenState.set("OPEN_STATE_PAIMON", LuaValue.valueOf(OPEN_STATE_PAIMON));
			scriptConstOpenState.set("OPEN_STATE_PAIMON_NAVIGATION", LuaValue.valueOf(OPEN_STATE_PAIMON_NAVIGATION));
			scriptConstOpenState.set("OPEN_STATE_AVATAR_PROMOTE", LuaValue.valueOf(OPEN_STATE_AVATAR_PROMOTE));
			scriptConstOpenState.set("OPEN_STATE_AVATAR_TALENT", LuaValue.valueOf(OPEN_STATE_AVATAR_TALENT));
			scriptConstOpenState.set("OPEN_STATE_WEAPON_PROMOTE", LuaValue.valueOf(OPEN_STATE_WEAPON_PROMOTE));
			scriptConstOpenState.set("OPEN_STATE_WEAPON_AWAKEN", LuaValue.valueOf(OPEN_STATE_WEAPON_AWAKEN));
			scriptConstOpenState.set("OPEN_STATE_QUEST_REMIND", LuaValue.valueOf(OPEN_STATE_QUEST_REMIND));
			scriptConstOpenState.set("OPEN_STATE_GAME_GUIDE", LuaValue.valueOf(OPEN_STATE_GAME_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_COOK", LuaValue.valueOf(OPEN_STATE_COOK));
			scriptConstOpenState.set("OPEN_STATE_WEAPON_UPGRADE", LuaValue.valueOf(OPEN_STATE_WEAPON_UPGRADE));
			scriptConstOpenState.set("OPEN_STATE_RELIQUARY_UPGRADE", LuaValue.valueOf(OPEN_STATE_RELIQUARY_UPGRADE));
			scriptConstOpenState.set("OPEN_STATE_RELIQUARY_PROMOTE", LuaValue.valueOf(OPEN_STATE_RELIQUARY_PROMOTE));
			scriptConstOpenState.set("OPEN_STATE_WEAPON_PROMOTE_GUIDE", LuaValue.valueOf(OPEN_STATE_WEAPON_PROMOTE_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_WEAPON_CHANGE_GUIDE", LuaValue.valueOf(OPEN_STATE_WEAPON_CHANGE_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_PLAYER_LVUP_GUIDE", LuaValue.valueOf(OPEN_STATE_PLAYER_LVUP_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_FRESHMAN_GUIDE", LuaValue.valueOf(OPEN_STATE_FRESHMAN_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_SKIP_FRESHMAN_GUIDE", LuaValue.valueOf(OPEN_STATE_SKIP_FRESHMAN_GUIDE));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_MOVE_CAMERA", LuaValue.valueOf(OPEN_STATE_GUIDE_MOVE_CAMERA));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_SCALE_CAMERA", LuaValue.valueOf(OPEN_STATE_GUIDE_SCALE_CAMERA));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_KEYBOARD", LuaValue.valueOf(OPEN_STATE_GUIDE_KEYBOARD));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_MOVE", LuaValue.valueOf(OPEN_STATE_GUIDE_MOVE));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_JUMP", LuaValue.valueOf(OPEN_STATE_GUIDE_JUMP));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_SPRINT", LuaValue.valueOf(OPEN_STATE_GUIDE_SPRINT));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_MAP", LuaValue.valueOf(OPEN_STATE_GUIDE_MAP));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_ATTACK", LuaValue.valueOf(OPEN_STATE_GUIDE_ATTACK));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_FLY", LuaValue.valueOf(OPEN_STATE_GUIDE_FLY));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_TALENT", LuaValue.valueOf(OPEN_STATE_GUIDE_TALENT));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_RELIC", LuaValue.valueOf(OPEN_STATE_GUIDE_RELIC));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_RELIC_PROM", LuaValue.valueOf(OPEN_STATE_GUIDE_RELIC_PROM));
			scriptConstOpenState.set("OPEN_STATE_COMBINE", LuaValue.valueOf(OPEN_STATE_COMBINE));
			scriptConstOpenState.set("OPEN_STATE_GACHA", LuaValue.valueOf(OPEN_STATE_GACHA));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_GACHA", LuaValue.valueOf(OPEN_STATE_GUIDE_GACHA));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_TEAM", LuaValue.valueOf(OPEN_STATE_GUIDE_TEAM));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_PROUD", LuaValue.valueOf(OPEN_STATE_GUIDE_PROUD));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_AVATAR_PROMOTE", LuaValue.valueOf(OPEN_STATE_GUIDE_AVATAR_PROMOTE));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_ADVENTURE_CARD", LuaValue.valueOf(OPEN_STATE_GUIDE_ADVENTURE_CARD));
			scriptConstOpenState.set("OPEN_STATE_FORGE", LuaValue.valueOf(OPEN_STATE_FORGE));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_BAG", LuaValue.valueOf(OPEN_STATE_GUIDE_BAG));
			scriptConstOpenState.set("OPEN_STATE_EXPEDITION", LuaValue.valueOf(OPEN_STATE_EXPEDITION));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK", LuaValue.valueOf(OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_ADVENTURE_DUNGEON", LuaValue.valueOf(OPEN_STATE_GUIDE_ADVENTURE_DUNGEON));
			scriptConstOpenState.set("OPEN_STATE_TOWER", LuaValue.valueOf(OPEN_STATE_TOWER));
			scriptConstOpenState.set("OPEN_STATE_WORLD_STAMINA", LuaValue.valueOf(OPEN_STATE_WORLD_STAMINA));
			scriptConstOpenState.set("OPEN_STATE_TOWER_FIRST_ENTER", LuaValue.valueOf(OPEN_STATE_TOWER_FIRST_ENTER));
			scriptConstOpenState.set("OPEN_STATE_RESIN", LuaValue.valueOf(OPEN_STATE_RESIN));
			scriptConstOpenState.set("OPEN_STATE_WORLD_RESIN", LuaValue.valueOf(OPEN_STATE_WORLD_RESIN));
			scriptConstOpenState.set("OPEN_STATE_LIMIT_REGION_FRESHMEAT", LuaValue.valueOf(OPEN_STATE_LIMIT_REGION_FRESHMEAT));
			scriptConstOpenState.set("OPEN_STATE_LIMIT_REGION_GLOBAL", LuaValue.valueOf(OPEN_STATE_LIMIT_REGION_GLOBAL));
			scriptConstOpenState.set("OPEN_STATE_MULTIPLAYER", LuaValue.valueOf(OPEN_STATE_MULTIPLAYER));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_MOUSEPC", LuaValue.valueOf(OPEN_STATE_GUIDE_MOUSEPC));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_MULTIPLAYER", LuaValue.valueOf(OPEN_STATE_GUIDE_MULTIPLAYER));
			scriptConstOpenState.set("OPEN_STATE_GUIDE_DUNGEONREWARD", LuaValue.valueOf(OPEN_STATE_GUIDE_DUNGEONREWARD));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_PAIMON", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_PAIMON));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_CITY", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_CITY));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_BLACKSMITH", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_BLACKSMITH));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_GROCERY", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_GROCERY));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_FOOD", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_FOOD));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_SEA_LAMP", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_SEA_LAMP));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR));
			scriptConstOpenState.set("OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT", LuaValue.valueOf(OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT));
			scriptConstOpenState.set("OPEN_ADVENTURE_MANUAL", LuaValue.valueOf(OPEN_ADVENTURE_MANUAL));
			scriptConstOpenState.set("OPEN_ADVENTURE_MANUAL_CITY_MENGDE", LuaValue.valueOf(OPEN_ADVENTURE_MANUAL_CITY_MENGDE));
			scriptConstOpenState.set("OPEN_ADVENTURE_MANUAL_CITY_LIYUE", LuaValue.valueOf(OPEN_ADVENTURE_MANUAL_CITY_LIYUE));
			scriptConstOpenState.set("OPEN_ADVENTURE_MANUAL_MONSTER", LuaValue.valueOf(OPEN_ADVENTURE_MANUAL_MONSTER));
			scriptConstOpenState.set("OPEN_STATE_ACTIVITY_SEALAMP", LuaValue.valueOf(OPEN_STATE_ACTIVITY_SEALAMP));
			scriptConstOpenState.set("OPEN_STATE_ACTIVITY_SEALAMP_TAB2", LuaValue.valueOf(OPEN_STATE_ACTIVITY_SEALAMP_TAB2));
			scriptConstOpenState.set("OPEN_STATE_ACTIVITY_SEALAMP_TAB3", LuaValue.valueOf(OPEN_STATE_ACTIVITY_SEALAMP_TAB3));
			env.set("OpenStateType", scriptConstOpenState);
			env.get("package").get("loaded").set("OpenStateType", scriptConstOpenState);
			return env;
		}
	}
}
