version: '3.9'

services:
  server:
    image: grasscutter:1.0
    build: .
    volumes:
      - ./resources:/app/resources
      - ./data:/app/data
      - ./config.json:/app/config.json
      - ./keystore.p12:/app/keystore.p12
    network_mode: service:mongodb
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
  
  config-gen:
    image: grasscutter:1.0
    build: .
    volumes:
      - ./:/app/src
    entrypoint: ["/bin/sh", "-c", "java -jar grasscutter.jar; mv config.json ./src; echo config generated"]
    profiles:
      - donotstart

  mongodb:
    image: mongo:5.0.7
    ports:
      - 80:80
      - 443:443
      - 8888:8888/tcp
      - 8888:8888/udp
      - 27017:27017
      - 22102:22102/tcp
      - 22102:22102/udp
    volumes:
      - ./docker_data/mongo:/data/db
