package emu.grasscutter.game.dungeons.enums;

public enum DungunEntryType {
    DUNGEN_ENTRY_TYPE_NONE,
    DUNGEN_ENTRY_TYPE_AVATAR_EXP,
    DUNGEN_ENTRY_TYPE_WEAPON_PROMOTE,
    DUNGEN_ENTRY_TYPE_AVATAR_TALENT,
    DUNGEN_ENTRY_TYPE_RELIQUARY,
    DUNGEN_ENTRY_TYPE_SCOIN,
    DUNGEON_ENTRY_TYPE_OBSCURAE,
    DUNGEON_ENTRY_TYPE_NORMAL
}
