// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatInfo.proto

package emu.grasscutter.net.proto;

public final class ChatInfoOuterClass {
  private ChatInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    int getTime();

    /**
     * <code>uint32 uid = 2;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>uint32 sequence = 3;</code>
     * @return The sequence.
     */
    int getSequence();

    /**
     * <code>uint32 toUid = 4;</code>
     * @return The toUid.
     */
    int getToUid();

    /**
     * <code>bool isRead = 5;</code>
     * @return The isRead.
     */
    boolean getIsRead();

    /**
     * <code>string text = 100;</code>
     * @return Whether the text field is set.
     */
    boolean hasText();
    /**
     * <code>string text = 100;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 100;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>uint32 icon = 101;</code>
     * @return Whether the icon field is set.
     */
    boolean hasIcon();
    /**
     * <code>uint32 icon = 101;</code>
     * @return The icon.
     */
    int getIcon();

    /**
     * <code>.SystemHint systemHint = 102;</code>
     * @return Whether the systemHint field is set.
     */
    boolean hasSystemHint();
    /**
     * <code>.SystemHint systemHint = 102;</code>
     * @return The systemHint.
     */
    emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint getSystemHint();
    /**
     * <code>.SystemHint systemHint = 102;</code>
     */
    emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder getSystemHintOrBuilder();

    public emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.ContentCase getContentCase();
  }
  /**
   * Protobuf type {@code ChatInfo}
   */
  public static final class ChatInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatInfo)
      ChatInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatInfo.newBuilder() to construct.
    private ChatInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readUInt32();
              break;
            }
            case 16: {

              uid_ = input.readUInt32();
              break;
            }
            case 24: {

              sequence_ = input.readUInt32();
              break;
            }
            case 32: {

              toUid_ = input.readUInt32();
              break;
            }
            case 40: {

              isRead_ = input.readBool();
              break;
            }
            case 802: {
              java.lang.String s = input.readStringRequireUtf8();
              contentCase_ = 100;
              content_ = s;
              break;
            }
            case 808: {
              contentCase_ = 101;
              content_ = input.readUInt32();
              break;
            }
            case 818: {
              emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder subBuilder = null;
              if (contentCase_ == 102) {
                subBuilder = ((emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_).toBuilder();
              }
              content_ =
                  input.readMessage(emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_);
                content_ = subBuilder.buildPartial();
              }
              contentCase_ = 102;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.ChatInfoOuterClass.internal_static_ChatInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.ChatInfoOuterClass.internal_static_ChatInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.class, emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.Builder.class);
    }

    private int contentCase_ = 0;
    private java.lang.Object content_;
    public enum ContentCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      TEXT(100),
      ICON(101),
      SYSTEMHINT(102),
      CONTENT_NOT_SET(0);
      private final int value;
      private ContentCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContentCase forNumber(int value) {
        switch (value) {
          case 100: return TEXT;
          case 101: return ICON;
          case 102: return SYSTEMHINT;
          case 0: return CONTENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ContentCase
    getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private int time_;
    /**
     * <code>uint32 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public int getTime() {
      return time_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private int uid_;
    /**
     * <code>uint32 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private int sequence_;
    /**
     * <code>uint32 sequence = 3;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }

    public static final int TOUID_FIELD_NUMBER = 4;
    private int toUid_;
    /**
     * <code>uint32 toUid = 4;</code>
     * @return The toUid.
     */
    @java.lang.Override
    public int getToUid() {
      return toUid_;
    }

    public static final int ISREAD_FIELD_NUMBER = 5;
    private boolean isRead_;
    /**
     * <code>bool isRead = 5;</code>
     * @return The isRead.
     */
    @java.lang.Override
    public boolean getIsRead() {
      return isRead_;
    }

    public static final int TEXT_FIELD_NUMBER = 100;
    /**
     * <code>string text = 100;</code>
     * @return Whether the text field is set.
     */
    public boolean hasText() {
      return contentCase_ == 100;
    }
    /**
     * <code>string text = 100;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = "";
      if (contentCase_ == 100) {
        ref = content_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (contentCase_ == 100) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string text = 100;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = "";
      if (contentCase_ == 100) {
        ref = content_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (contentCase_ == 100) {
          content_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 101;
    /**
     * <code>uint32 icon = 101;</code>
     * @return Whether the icon field is set.
     */
    @java.lang.Override
    public boolean hasIcon() {
      return contentCase_ == 101;
    }
    /**
     * <code>uint32 icon = 101;</code>
     * @return The icon.
     */
    @java.lang.Override
    public int getIcon() {
      if (contentCase_ == 101) {
        return (java.lang.Integer) content_;
      }
      return 0;
    }

    public static final int SYSTEMHINT_FIELD_NUMBER = 102;
    /**
     * <code>.SystemHint systemHint = 102;</code>
     * @return Whether the systemHint field is set.
     */
    @java.lang.Override
    public boolean hasSystemHint() {
      return contentCase_ == 102;
    }
    /**
     * <code>.SystemHint systemHint = 102;</code>
     * @return The systemHint.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint getSystemHint() {
      if (contentCase_ == 102) {
         return (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_;
      }
      return emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
    }
    /**
     * <code>.SystemHint systemHint = 102;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder getSystemHintOrBuilder() {
      if (contentCase_ == 102) {
         return (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_;
      }
      return emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0) {
        output.writeUInt32(1, time_);
      }
      if (uid_ != 0) {
        output.writeUInt32(2, uid_);
      }
      if (sequence_ != 0) {
        output.writeUInt32(3, sequence_);
      }
      if (toUid_ != 0) {
        output.writeUInt32(4, toUid_);
      }
      if (isRead_ != false) {
        output.writeBool(5, isRead_);
      }
      if (contentCase_ == 100) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 100, content_);
      }
      if (contentCase_ == 101) {
        output.writeUInt32(
            101, (int)((java.lang.Integer) content_));
      }
      if (contentCase_ == 102) {
        output.writeMessage(102, (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, time_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, uid_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sequence_);
      }
      if (toUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, toUid_);
      }
      if (isRead_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isRead_);
      }
      if (contentCase_ == 100) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, content_);
      }
      if (contentCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              101, (int)((java.lang.Integer) content_));
      }
      if (contentCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo other = (emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo) obj;

      if (getTime()
          != other.getTime()) return false;
      if (getUid()
          != other.getUid()) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (getToUid()
          != other.getToUid()) return false;
      if (getIsRead()
          != other.getIsRead()) return false;
      if (!getContentCase().equals(other.getContentCase())) return false;
      switch (contentCase_) {
        case 100:
          if (!getText()
              .equals(other.getText())) return false;
          break;
        case 101:
          if (getIcon()
              != other.getIcon()) return false;
          break;
        case 102:
          if (!getSystemHint()
              .equals(other.getSystemHint())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + TOUID_FIELD_NUMBER;
      hash = (53 * hash) + getToUid();
      hash = (37 * hash) + ISREAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRead());
      switch (contentCase_) {
        case 100:
          hash = (37 * hash) + TEXT_FIELD_NUMBER;
          hash = (53 * hash) + getText().hashCode();
          break;
        case 101:
          hash = (37 * hash) + ICON_FIELD_NUMBER;
          hash = (53 * hash) + getIcon();
          break;
        case 102:
          hash = (37 * hash) + SYSTEMHINT_FIELD_NUMBER;
          hash = (53 * hash) + getSystemHint().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatInfo)
        emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.ChatInfoOuterClass.internal_static_ChatInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.ChatInfoOuterClass.internal_static_ChatInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.class, emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0;

        uid_ = 0;

        sequence_ = 0;

        toUid_ = 0;

        isRead_ = false;

        contentCase_ = 0;
        content_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.ChatInfoOuterClass.internal_static_ChatInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo build() {
        emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo buildPartial() {
        emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo result = new emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo(this);
        result.time_ = time_;
        result.uid_ = uid_;
        result.sequence_ = sequence_;
        result.toUid_ = toUid_;
        result.isRead_ = isRead_;
        if (contentCase_ == 100) {
          result.content_ = content_;
        }
        if (contentCase_ == 101) {
          result.content_ = content_;
        }
        if (contentCase_ == 102) {
          if (systemHintBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = systemHintBuilder_.build();
          }
        }
        result.contentCase_ = contentCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo) {
          return mergeFrom((emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo other) {
        if (other == emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo.getDefaultInstance()) return this;
        if (other.getTime() != 0) {
          setTime(other.getTime());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getToUid() != 0) {
          setToUid(other.getToUid());
        }
        if (other.getIsRead() != false) {
          setIsRead(other.getIsRead());
        }
        switch (other.getContentCase()) {
          case TEXT: {
            contentCase_ = 100;
            content_ = other.content_;
            onChanged();
            break;
          }
          case ICON: {
            setIcon(other.getIcon());
            break;
          }
          case SYSTEMHINT: {
            mergeSystemHint(other.getSystemHint());
            break;
          }
          case CONTENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int contentCase_ = 0;
      private java.lang.Object content_;
      public ContentCase
          getContentCase() {
        return ContentCase.forNumber(
            contentCase_);
      }

      public Builder clearContent() {
        contentCase_ = 0;
        content_ = null;
        onChanged();
        return this;
      }


      private int time_ ;
      /**
       * <code>uint32 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public int getTime() {
        return time_;
      }
      /**
       * <code>uint32 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(int value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>uint32 uid = 2;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>uint32 uid = 2;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <code>uint32 sequence = 3;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>uint32 sequence = 3;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(int value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sequence = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        
        sequence_ = 0;
        onChanged();
        return this;
      }

      private int toUid_ ;
      /**
       * <code>uint32 toUid = 4;</code>
       * @return The toUid.
       */
      @java.lang.Override
      public int getToUid() {
        return toUid_;
      }
      /**
       * <code>uint32 toUid = 4;</code>
       * @param value The toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUid(int value) {
        
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 toUid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUid() {
        
        toUid_ = 0;
        onChanged();
        return this;
      }

      private boolean isRead_ ;
      /**
       * <code>bool isRead = 5;</code>
       * @return The isRead.
       */
      @java.lang.Override
      public boolean getIsRead() {
        return isRead_;
      }
      /**
       * <code>bool isRead = 5;</code>
       * @param value The isRead to set.
       * @return This builder for chaining.
       */
      public Builder setIsRead(boolean value) {
        
        isRead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isRead = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsRead() {
        
        isRead_ = false;
        onChanged();
        return this;
      }

      /**
       * <code>string text = 100;</code>
       * @return Whether the text field is set.
       */
      @java.lang.Override
      public boolean hasText() {
        return contentCase_ == 100;
      }
      /**
       * <code>string text = 100;</code>
       * @return The text.
       */
      @java.lang.Override
      public java.lang.String getText() {
        java.lang.Object ref = "";
        if (contentCase_ == 100) {
          ref = content_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (contentCase_ == 100) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 100;</code>
       * @return The bytes for text.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = "";
        if (contentCase_ == 100) {
          ref = content_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (contentCase_ == 100) {
            content_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 100;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  contentCase_ = 100;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 100;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        if (contentCase_ == 100) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string text = 100;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        contentCase_ = 100;
        content_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>uint32 icon = 101;</code>
       * @return Whether the icon field is set.
       */
      public boolean hasIcon() {
        return contentCase_ == 101;
      }
      /**
       * <code>uint32 icon = 101;</code>
       * @return The icon.
       */
      public int getIcon() {
        if (contentCase_ == 101) {
          return (java.lang.Integer) content_;
        }
        return 0;
      }
      /**
       * <code>uint32 icon = 101;</code>
       * @param value The icon to set.
       * @return This builder for chaining.
       */
      public Builder setIcon(int value) {
        contentCase_ = 101;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 icon = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearIcon() {
        if (contentCase_ == 101) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder> systemHintBuilder_;
      /**
       * <code>.SystemHint systemHint = 102;</code>
       * @return Whether the systemHint field is set.
       */
      @java.lang.Override
      public boolean hasSystemHint() {
        return contentCase_ == 102;
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       * @return The systemHint.
       */
      @java.lang.Override
      public emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint getSystemHint() {
        if (systemHintBuilder_ == null) {
          if (contentCase_ == 102) {
            return (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_;
          }
          return emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
        } else {
          if (contentCase_ == 102) {
            return systemHintBuilder_.getMessage();
          }
          return emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
        }
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      public Builder setSystemHint(emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint value) {
        if (systemHintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          systemHintBuilder_.setMessage(value);
        }
        contentCase_ = 102;
        return this;
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      public Builder setSystemHint(
          emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder builderForValue) {
        if (systemHintBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          systemHintBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 102;
        return this;
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      public Builder mergeSystemHint(emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint value) {
        if (systemHintBuilder_ == null) {
          if (contentCase_ == 102 &&
              content_ != emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance()) {
            content_ = emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.newBuilder((emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 102) {
            systemHintBuilder_.mergeFrom(value);
          }
          systemHintBuilder_.setMessage(value);
        }
        contentCase_ = 102;
        return this;
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      public Builder clearSystemHint() {
        if (systemHintBuilder_ == null) {
          if (contentCase_ == 102) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 102) {
            contentCase_ = 0;
            content_ = null;
          }
          systemHintBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      public emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder getSystemHintBuilder() {
        return getSystemHintFieldBuilder().getBuilder();
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      @java.lang.Override
      public emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder getSystemHintOrBuilder() {
        if ((contentCase_ == 102) && (systemHintBuilder_ != null)) {
          return systemHintBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 102) {
            return (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_;
          }
          return emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
        }
      }
      /**
       * <code>.SystemHint systemHint = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder> 
          getSystemHintFieldBuilder() {
        if (systemHintBuilder_ == null) {
          if (!(contentCase_ == 102)) {
            content_ = emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.getDefaultInstance();
          }
          systemHintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint.Builder, emu.grasscutter.net.proto.SystemHintOuterClass.SystemHintOrBuilder>(
                  (emu.grasscutter.net.proto.SystemHintOuterClass.SystemHint) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 102;
        onChanged();;
        return systemHintBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatInfo)
    }

    // @@protoc_insertion_point(class_scope:ChatInfo)
    private static final emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo();
    }

    public static emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatInfo>
        PARSER = new com.google.protobuf.AbstractParser<ChatInfo>() {
      @java.lang.Override
      public ChatInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.ChatInfoOuterClass.ChatInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ChatInfo.proto\032\020SystemHint.proto\"\244\001\n\010C" +
      "hatInfo\022\014\n\004time\030\001 \001(\r\022\013\n\003uid\030\002 \001(\r\022\020\n\010se" +
      "quence\030\003 \001(\r\022\r\n\005toUid\030\004 \001(\r\022\016\n\006isRead\030\005 " +
      "\001(\010\022\016\n\004text\030d \001(\tH\000\022\016\n\004icon\030e \001(\rH\000\022!\n\ns" +
      "ystemHint\030f \001(\0132\013.SystemHintH\000B\t\n\007conten" +
      "tB\033\n\031emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.SystemHintOuterClass.getDescriptor(),
        });
    internal_static_ChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatInfo_descriptor,
        new java.lang.String[] { "Time", "Uid", "Sequence", "ToUid", "IsRead", "Text", "Icon", "SystemHint", "Content", });
    emu.grasscutter.net.proto.SystemHintOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
