// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EvtCreateGadgetNotify.proto

package emu.grasscutter.net.proto;

public final class EvtCreateGadgetNotifyOuterClass {
  private EvtCreateGadgetNotifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EvtCreateGadgetNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EvtCreateGadgetNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ForwardType forwardType = 1;</code>
     * @return The enum numeric value on the wire for forwardType.
     */
    int getForwardTypeValue();
    /**
     * <code>.ForwardType forwardType = 1;</code>
     * @return The forwardType.
     */
    emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType getForwardType();

    /**
     * <code>uint32 entityId = 2;</code>
     * @return The entityId.
     */
    int getEntityId();

    /**
     * <code>uint32 configId = 3;</code>
     * @return The configId.
     */
    int getConfigId();

    /**
     * <code>uint32 campId = 4;</code>
     * @return The campId.
     */
    int getCampId();

    /**
     * <code>uint32 campType = 5;</code>
     * @return The campType.
     */
    int getCampType();

    /**
     * <code>.Vector initPos = 6;</code>
     * @return Whether the initPos field is set.
     */
    boolean hasInitPos();
    /**
     * <code>.Vector initPos = 6;</code>
     * @return The initPos.
     */
    emu.grasscutter.net.proto.VectorOuterClass.Vector getInitPos();
    /**
     * <code>.Vector initPos = 6;</code>
     */
    emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitPosOrBuilder();

    /**
     * <code>.Vector initEulerAngles = 7;</code>
     * @return Whether the initEulerAngles field is set.
     */
    boolean hasInitEulerAngles();
    /**
     * <code>.Vector initEulerAngles = 7;</code>
     * @return The initEulerAngles.
     */
    emu.grasscutter.net.proto.VectorOuterClass.Vector getInitEulerAngles();
    /**
     * <code>.Vector initEulerAngles = 7;</code>
     */
    emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitEulerAnglesOrBuilder();

    /**
     * <code>uint64 guid = 8;</code>
     * @return The guid.
     */
    long getGuid();

    /**
     * <code>uint32 ownerEntityId = 9;</code>
     * @return The ownerEntityId.
     */
    int getOwnerEntityId();

    /**
     * <code>uint32 targetEntityId = 10;</code>
     * @return The targetEntityId.
     */
    int getTargetEntityId();

    /**
     * <code>bool isAsyncLoad = 11;</code>
     * @return The isAsyncLoad.
     */
    boolean getIsAsyncLoad();

    /**
     * <code>uint32 targetLockPointIndex = 12;</code>
     * @return The targetLockPointIndex.
     */
    int getTargetLockPointIndex();

    /**
     * <code>uint32 roomId = 13;</code>
     * @return The roomId.
     */
    int getRoomId();

    /**
     * <code>uint32 propOwnerEntityId = 14;</code>
     * @return The propOwnerEntityId.
     */
    int getPropOwnerEntityId();

    /**
     * <code>bool sightGroupWithOwner = 15;</code>
     * @return The sightGroupWithOwner.
     */
    boolean getSightGroupWithOwner();
  }
  /**
   * Protobuf type {@code EvtCreateGadgetNotify}
   */
  public static final class EvtCreateGadgetNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EvtCreateGadgetNotify)
      EvtCreateGadgetNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EvtCreateGadgetNotify.newBuilder() to construct.
    private EvtCreateGadgetNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EvtCreateGadgetNotify() {
      forwardType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EvtCreateGadgetNotify();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EvtCreateGadgetNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              forwardType_ = rawValue;
              break;
            }
            case 16: {

              entityId_ = input.readUInt32();
              break;
            }
            case 24: {

              configId_ = input.readUInt32();
              break;
            }
            case 32: {

              campId_ = input.readUInt32();
              break;
            }
            case 40: {

              campType_ = input.readUInt32();
              break;
            }
            case 50: {
              emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder subBuilder = null;
              if (initPos_ != null) {
                subBuilder = initPos_.toBuilder();
              }
              initPos_ = input.readMessage(emu.grasscutter.net.proto.VectorOuterClass.Vector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(initPos_);
                initPos_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder subBuilder = null;
              if (initEulerAngles_ != null) {
                subBuilder = initEulerAngles_.toBuilder();
              }
              initEulerAngles_ = input.readMessage(emu.grasscutter.net.proto.VectorOuterClass.Vector.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(initEulerAngles_);
                initEulerAngles_ = subBuilder.buildPartial();
              }

              break;
            }
            case 64: {

              guid_ = input.readUInt64();
              break;
            }
            case 72: {

              ownerEntityId_ = input.readUInt32();
              break;
            }
            case 80: {

              targetEntityId_ = input.readUInt32();
              break;
            }
            case 88: {

              isAsyncLoad_ = input.readBool();
              break;
            }
            case 96: {

              targetLockPointIndex_ = input.readUInt32();
              break;
            }
            case 104: {

              roomId_ = input.readUInt32();
              break;
            }
            case 112: {

              propOwnerEntityId_ = input.readUInt32();
              break;
            }
            case 120: {

              sightGroupWithOwner_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.internal_static_EvtCreateGadgetNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.internal_static_EvtCreateGadgetNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.class, emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.Builder.class);
    }

    public static final int FORWARDTYPE_FIELD_NUMBER = 1;
    private int forwardType_;
    /**
     * <code>.ForwardType forwardType = 1;</code>
     * @return The enum numeric value on the wire for forwardType.
     */
    @java.lang.Override public int getForwardTypeValue() {
      return forwardType_;
    }
    /**
     * <code>.ForwardType forwardType = 1;</code>
     * @return The forwardType.
     */
    @java.lang.Override public emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType getForwardType() {
      @SuppressWarnings("deprecation")
      emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType result = emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.valueOf(forwardType_);
      return result == null ? emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.UNRECOGNIZED : result;
    }

    public static final int ENTITYID_FIELD_NUMBER = 2;
    private int entityId_;
    /**
     * <code>uint32 entityId = 2;</code>
     * @return The entityId.
     */
    @java.lang.Override
    public int getEntityId() {
      return entityId_;
    }

    public static final int CONFIGID_FIELD_NUMBER = 3;
    private int configId_;
    /**
     * <code>uint32 configId = 3;</code>
     * @return The configId.
     */
    @java.lang.Override
    public int getConfigId() {
      return configId_;
    }

    public static final int CAMPID_FIELD_NUMBER = 4;
    private int campId_;
    /**
     * <code>uint32 campId = 4;</code>
     * @return The campId.
     */
    @java.lang.Override
    public int getCampId() {
      return campId_;
    }

    public static final int CAMPTYPE_FIELD_NUMBER = 5;
    private int campType_;
    /**
     * <code>uint32 campType = 5;</code>
     * @return The campType.
     */
    @java.lang.Override
    public int getCampType() {
      return campType_;
    }

    public static final int INITPOS_FIELD_NUMBER = 6;
    private emu.grasscutter.net.proto.VectorOuterClass.Vector initPos_;
    /**
     * <code>.Vector initPos = 6;</code>
     * @return Whether the initPos field is set.
     */
    @java.lang.Override
    public boolean hasInitPos() {
      return initPos_ != null;
    }
    /**
     * <code>.Vector initPos = 6;</code>
     * @return The initPos.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.VectorOuterClass.Vector getInitPos() {
      return initPos_ == null ? emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initPos_;
    }
    /**
     * <code>.Vector initPos = 6;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitPosOrBuilder() {
      return getInitPos();
    }

    public static final int INITEULERANGLES_FIELD_NUMBER = 7;
    private emu.grasscutter.net.proto.VectorOuterClass.Vector initEulerAngles_;
    /**
     * <code>.Vector initEulerAngles = 7;</code>
     * @return Whether the initEulerAngles field is set.
     */
    @java.lang.Override
    public boolean hasInitEulerAngles() {
      return initEulerAngles_ != null;
    }
    /**
     * <code>.Vector initEulerAngles = 7;</code>
     * @return The initEulerAngles.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.VectorOuterClass.Vector getInitEulerAngles() {
      return initEulerAngles_ == null ? emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initEulerAngles_;
    }
    /**
     * <code>.Vector initEulerAngles = 7;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitEulerAnglesOrBuilder() {
      return getInitEulerAngles();
    }

    public static final int GUID_FIELD_NUMBER = 8;
    private long guid_;
    /**
     * <code>uint64 guid = 8;</code>
     * @return The guid.
     */
    @java.lang.Override
    public long getGuid() {
      return guid_;
    }

    public static final int OWNERENTITYID_FIELD_NUMBER = 9;
    private int ownerEntityId_;
    /**
     * <code>uint32 ownerEntityId = 9;</code>
     * @return The ownerEntityId.
     */
    @java.lang.Override
    public int getOwnerEntityId() {
      return ownerEntityId_;
    }

    public static final int TARGETENTITYID_FIELD_NUMBER = 10;
    private int targetEntityId_;
    /**
     * <code>uint32 targetEntityId = 10;</code>
     * @return The targetEntityId.
     */
    @java.lang.Override
    public int getTargetEntityId() {
      return targetEntityId_;
    }

    public static final int ISASYNCLOAD_FIELD_NUMBER = 11;
    private boolean isAsyncLoad_;
    /**
     * <code>bool isAsyncLoad = 11;</code>
     * @return The isAsyncLoad.
     */
    @java.lang.Override
    public boolean getIsAsyncLoad() {
      return isAsyncLoad_;
    }

    public static final int TARGETLOCKPOINTINDEX_FIELD_NUMBER = 12;
    private int targetLockPointIndex_;
    /**
     * <code>uint32 targetLockPointIndex = 12;</code>
     * @return The targetLockPointIndex.
     */
    @java.lang.Override
    public int getTargetLockPointIndex() {
      return targetLockPointIndex_;
    }

    public static final int ROOMID_FIELD_NUMBER = 13;
    private int roomId_;
    /**
     * <code>uint32 roomId = 13;</code>
     * @return The roomId.
     */
    @java.lang.Override
    public int getRoomId() {
      return roomId_;
    }

    public static final int PROPOWNERENTITYID_FIELD_NUMBER = 14;
    private int propOwnerEntityId_;
    /**
     * <code>uint32 propOwnerEntityId = 14;</code>
     * @return The propOwnerEntityId.
     */
    @java.lang.Override
    public int getPropOwnerEntityId() {
      return propOwnerEntityId_;
    }

    public static final int SIGHTGROUPWITHOWNER_FIELD_NUMBER = 15;
    private boolean sightGroupWithOwner_;
    /**
     * <code>bool sightGroupWithOwner = 15;</code>
     * @return The sightGroupWithOwner.
     */
    @java.lang.Override
    public boolean getSightGroupWithOwner() {
      return sightGroupWithOwner_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (forwardType_ != emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.ForwardLocal.getNumber()) {
        output.writeEnum(1, forwardType_);
      }
      if (entityId_ != 0) {
        output.writeUInt32(2, entityId_);
      }
      if (configId_ != 0) {
        output.writeUInt32(3, configId_);
      }
      if (campId_ != 0) {
        output.writeUInt32(4, campId_);
      }
      if (campType_ != 0) {
        output.writeUInt32(5, campType_);
      }
      if (initPos_ != null) {
        output.writeMessage(6, getInitPos());
      }
      if (initEulerAngles_ != null) {
        output.writeMessage(7, getInitEulerAngles());
      }
      if (guid_ != 0L) {
        output.writeUInt64(8, guid_);
      }
      if (ownerEntityId_ != 0) {
        output.writeUInt32(9, ownerEntityId_);
      }
      if (targetEntityId_ != 0) {
        output.writeUInt32(10, targetEntityId_);
      }
      if (isAsyncLoad_ != false) {
        output.writeBool(11, isAsyncLoad_);
      }
      if (targetLockPointIndex_ != 0) {
        output.writeUInt32(12, targetLockPointIndex_);
      }
      if (roomId_ != 0) {
        output.writeUInt32(13, roomId_);
      }
      if (propOwnerEntityId_ != 0) {
        output.writeUInt32(14, propOwnerEntityId_);
      }
      if (sightGroupWithOwner_ != false) {
        output.writeBool(15, sightGroupWithOwner_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (forwardType_ != emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.ForwardLocal.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, forwardType_);
      }
      if (entityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, entityId_);
      }
      if (configId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, configId_);
      }
      if (campId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, campId_);
      }
      if (campType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, campType_);
      }
      if (initPos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getInitPos());
      }
      if (initEulerAngles_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getInitEulerAngles());
      }
      if (guid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, guid_);
      }
      if (ownerEntityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, ownerEntityId_);
      }
      if (targetEntityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, targetEntityId_);
      }
      if (isAsyncLoad_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isAsyncLoad_);
      }
      if (targetLockPointIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, targetLockPointIndex_);
      }
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, roomId_);
      }
      if (propOwnerEntityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, propOwnerEntityId_);
      }
      if (sightGroupWithOwner_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, sightGroupWithOwner_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify other = (emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify) obj;

      if (forwardType_ != other.forwardType_) return false;
      if (getEntityId()
          != other.getEntityId()) return false;
      if (getConfigId()
          != other.getConfigId()) return false;
      if (getCampId()
          != other.getCampId()) return false;
      if (getCampType()
          != other.getCampType()) return false;
      if (hasInitPos() != other.hasInitPos()) return false;
      if (hasInitPos()) {
        if (!getInitPos()
            .equals(other.getInitPos())) return false;
      }
      if (hasInitEulerAngles() != other.hasInitEulerAngles()) return false;
      if (hasInitEulerAngles()) {
        if (!getInitEulerAngles()
            .equals(other.getInitEulerAngles())) return false;
      }
      if (getGuid()
          != other.getGuid()) return false;
      if (getOwnerEntityId()
          != other.getOwnerEntityId()) return false;
      if (getTargetEntityId()
          != other.getTargetEntityId()) return false;
      if (getIsAsyncLoad()
          != other.getIsAsyncLoad()) return false;
      if (getTargetLockPointIndex()
          != other.getTargetLockPointIndex()) return false;
      if (getRoomId()
          != other.getRoomId()) return false;
      if (getPropOwnerEntityId()
          != other.getPropOwnerEntityId()) return false;
      if (getSightGroupWithOwner()
          != other.getSightGroupWithOwner()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORWARDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + forwardType_;
      hash = (37 * hash) + ENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getEntityId();
      hash = (37 * hash) + CONFIGID_FIELD_NUMBER;
      hash = (53 * hash) + getConfigId();
      hash = (37 * hash) + CAMPID_FIELD_NUMBER;
      hash = (53 * hash) + getCampId();
      hash = (37 * hash) + CAMPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCampType();
      if (hasInitPos()) {
        hash = (37 * hash) + INITPOS_FIELD_NUMBER;
        hash = (53 * hash) + getInitPos().hashCode();
      }
      if (hasInitEulerAngles()) {
        hash = (37 * hash) + INITEULERANGLES_FIELD_NUMBER;
        hash = (53 * hash) + getInitEulerAngles().hashCode();
      }
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGuid());
      hash = (37 * hash) + OWNERENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerEntityId();
      hash = (37 * hash) + TARGETENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetEntityId();
      hash = (37 * hash) + ISASYNCLOAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAsyncLoad());
      hash = (37 * hash) + TARGETLOCKPOINTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getTargetLockPointIndex();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      hash = (37 * hash) + PROPOWNERENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getPropOwnerEntityId();
      hash = (37 * hash) + SIGHTGROUPWITHOWNER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSightGroupWithOwner());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EvtCreateGadgetNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EvtCreateGadgetNotify)
        emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.internal_static_EvtCreateGadgetNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.internal_static_EvtCreateGadgetNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.class, emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        forwardType_ = 0;

        entityId_ = 0;

        configId_ = 0;

        campId_ = 0;

        campType_ = 0;

        if (initPosBuilder_ == null) {
          initPos_ = null;
        } else {
          initPos_ = null;
          initPosBuilder_ = null;
        }
        if (initEulerAnglesBuilder_ == null) {
          initEulerAngles_ = null;
        } else {
          initEulerAngles_ = null;
          initEulerAnglesBuilder_ = null;
        }
        guid_ = 0L;

        ownerEntityId_ = 0;

        targetEntityId_ = 0;

        isAsyncLoad_ = false;

        targetLockPointIndex_ = 0;

        roomId_ = 0;

        propOwnerEntityId_ = 0;

        sightGroupWithOwner_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.internal_static_EvtCreateGadgetNotify_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify build() {
        emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify buildPartial() {
        emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify result = new emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify(this);
        result.forwardType_ = forwardType_;
        result.entityId_ = entityId_;
        result.configId_ = configId_;
        result.campId_ = campId_;
        result.campType_ = campType_;
        if (initPosBuilder_ == null) {
          result.initPos_ = initPos_;
        } else {
          result.initPos_ = initPosBuilder_.build();
        }
        if (initEulerAnglesBuilder_ == null) {
          result.initEulerAngles_ = initEulerAngles_;
        } else {
          result.initEulerAngles_ = initEulerAnglesBuilder_.build();
        }
        result.guid_ = guid_;
        result.ownerEntityId_ = ownerEntityId_;
        result.targetEntityId_ = targetEntityId_;
        result.isAsyncLoad_ = isAsyncLoad_;
        result.targetLockPointIndex_ = targetLockPointIndex_;
        result.roomId_ = roomId_;
        result.propOwnerEntityId_ = propOwnerEntityId_;
        result.sightGroupWithOwner_ = sightGroupWithOwner_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify) {
          return mergeFrom((emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify other) {
        if (other == emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify.getDefaultInstance()) return this;
        if (other.forwardType_ != 0) {
          setForwardTypeValue(other.getForwardTypeValue());
        }
        if (other.getEntityId() != 0) {
          setEntityId(other.getEntityId());
        }
        if (other.getConfigId() != 0) {
          setConfigId(other.getConfigId());
        }
        if (other.getCampId() != 0) {
          setCampId(other.getCampId());
        }
        if (other.getCampType() != 0) {
          setCampType(other.getCampType());
        }
        if (other.hasInitPos()) {
          mergeInitPos(other.getInitPos());
        }
        if (other.hasInitEulerAngles()) {
          mergeInitEulerAngles(other.getInitEulerAngles());
        }
        if (other.getGuid() != 0L) {
          setGuid(other.getGuid());
        }
        if (other.getOwnerEntityId() != 0) {
          setOwnerEntityId(other.getOwnerEntityId());
        }
        if (other.getTargetEntityId() != 0) {
          setTargetEntityId(other.getTargetEntityId());
        }
        if (other.getIsAsyncLoad() != false) {
          setIsAsyncLoad(other.getIsAsyncLoad());
        }
        if (other.getTargetLockPointIndex() != 0) {
          setTargetLockPointIndex(other.getTargetLockPointIndex());
        }
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (other.getPropOwnerEntityId() != 0) {
          setPropOwnerEntityId(other.getPropOwnerEntityId());
        }
        if (other.getSightGroupWithOwner() != false) {
          setSightGroupWithOwner(other.getSightGroupWithOwner());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int forwardType_ = 0;
      /**
       * <code>.ForwardType forwardType = 1;</code>
       * @return The enum numeric value on the wire for forwardType.
       */
      @java.lang.Override public int getForwardTypeValue() {
        return forwardType_;
      }
      /**
       * <code>.ForwardType forwardType = 1;</code>
       * @param value The enum numeric value on the wire for forwardType to set.
       * @return This builder for chaining.
       */
      public Builder setForwardTypeValue(int value) {
        
        forwardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ForwardType forwardType = 1;</code>
       * @return The forwardType.
       */
      @java.lang.Override
      public emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType getForwardType() {
        @SuppressWarnings("deprecation")
        emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType result = emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.valueOf(forwardType_);
        return result == null ? emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ForwardType forwardType = 1;</code>
       * @param value The forwardType to set.
       * @return This builder for chaining.
       */
      public Builder setForwardType(emu.grasscutter.net.proto.ForwardTypeOuterClass.ForwardType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        forwardType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ForwardType forwardType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearForwardType() {
        
        forwardType_ = 0;
        onChanged();
        return this;
      }

      private int entityId_ ;
      /**
       * <code>uint32 entityId = 2;</code>
       * @return The entityId.
       */
      @java.lang.Override
      public int getEntityId() {
        return entityId_;
      }
      /**
       * <code>uint32 entityId = 2;</code>
       * @param value The entityId to set.
       * @return This builder for chaining.
       */
      public Builder setEntityId(int value) {
        
        entityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 entityId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntityId() {
        
        entityId_ = 0;
        onChanged();
        return this;
      }

      private int configId_ ;
      /**
       * <code>uint32 configId = 3;</code>
       * @return The configId.
       */
      @java.lang.Override
      public int getConfigId() {
        return configId_;
      }
      /**
       * <code>uint32 configId = 3;</code>
       * @param value The configId to set.
       * @return This builder for chaining.
       */
      public Builder setConfigId(int value) {
        
        configId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 configId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfigId() {
        
        configId_ = 0;
        onChanged();
        return this;
      }

      private int campId_ ;
      /**
       * <code>uint32 campId = 4;</code>
       * @return The campId.
       */
      @java.lang.Override
      public int getCampId() {
        return campId_;
      }
      /**
       * <code>uint32 campId = 4;</code>
       * @param value The campId to set.
       * @return This builder for chaining.
       */
      public Builder setCampId(int value) {
        
        campId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 campId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCampId() {
        
        campId_ = 0;
        onChanged();
        return this;
      }

      private int campType_ ;
      /**
       * <code>uint32 campType = 5;</code>
       * @return The campType.
       */
      @java.lang.Override
      public int getCampType() {
        return campType_;
      }
      /**
       * <code>uint32 campType = 5;</code>
       * @param value The campType to set.
       * @return This builder for chaining.
       */
      public Builder setCampType(int value) {
        
        campType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 campType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCampType() {
        
        campType_ = 0;
        onChanged();
        return this;
      }

      private emu.grasscutter.net.proto.VectorOuterClass.Vector initPos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder> initPosBuilder_;
      /**
       * <code>.Vector initPos = 6;</code>
       * @return Whether the initPos field is set.
       */
      public boolean hasInitPos() {
        return initPosBuilder_ != null || initPos_ != null;
      }
      /**
       * <code>.Vector initPos = 6;</code>
       * @return The initPos.
       */
      public emu.grasscutter.net.proto.VectorOuterClass.Vector getInitPos() {
        if (initPosBuilder_ == null) {
          return initPos_ == null ? emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initPos_;
        } else {
          return initPosBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public Builder setInitPos(emu.grasscutter.net.proto.VectorOuterClass.Vector value) {
        if (initPosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initPos_ = value;
          onChanged();
        } else {
          initPosBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public Builder setInitPos(
          emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder builderForValue) {
        if (initPosBuilder_ == null) {
          initPos_ = builderForValue.build();
          onChanged();
        } else {
          initPosBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public Builder mergeInitPos(emu.grasscutter.net.proto.VectorOuterClass.Vector value) {
        if (initPosBuilder_ == null) {
          if (initPos_ != null) {
            initPos_ =
              emu.grasscutter.net.proto.VectorOuterClass.Vector.newBuilder(initPos_).mergeFrom(value).buildPartial();
          } else {
            initPos_ = value;
          }
          onChanged();
        } else {
          initPosBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public Builder clearInitPos() {
        if (initPosBuilder_ == null) {
          initPos_ = null;
          onChanged();
        } else {
          initPos_ = null;
          initPosBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder getInitPosBuilder() {
        
        onChanged();
        return getInitPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      public emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitPosOrBuilder() {
        if (initPosBuilder_ != null) {
          return initPosBuilder_.getMessageOrBuilder();
        } else {
          return initPos_ == null ?
              emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initPos_;
        }
      }
      /**
       * <code>.Vector initPos = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder> 
          getInitPosFieldBuilder() {
        if (initPosBuilder_ == null) {
          initPosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder>(
                  getInitPos(),
                  getParentForChildren(),
                  isClean());
          initPos_ = null;
        }
        return initPosBuilder_;
      }

      private emu.grasscutter.net.proto.VectorOuterClass.Vector initEulerAngles_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder> initEulerAnglesBuilder_;
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       * @return Whether the initEulerAngles field is set.
       */
      public boolean hasInitEulerAngles() {
        return initEulerAnglesBuilder_ != null || initEulerAngles_ != null;
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       * @return The initEulerAngles.
       */
      public emu.grasscutter.net.proto.VectorOuterClass.Vector getInitEulerAngles() {
        if (initEulerAnglesBuilder_ == null) {
          return initEulerAngles_ == null ? emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initEulerAngles_;
        } else {
          return initEulerAnglesBuilder_.getMessage();
        }
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public Builder setInitEulerAngles(emu.grasscutter.net.proto.VectorOuterClass.Vector value) {
        if (initEulerAnglesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initEulerAngles_ = value;
          onChanged();
        } else {
          initEulerAnglesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public Builder setInitEulerAngles(
          emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder builderForValue) {
        if (initEulerAnglesBuilder_ == null) {
          initEulerAngles_ = builderForValue.build();
          onChanged();
        } else {
          initEulerAnglesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public Builder mergeInitEulerAngles(emu.grasscutter.net.proto.VectorOuterClass.Vector value) {
        if (initEulerAnglesBuilder_ == null) {
          if (initEulerAngles_ != null) {
            initEulerAngles_ =
              emu.grasscutter.net.proto.VectorOuterClass.Vector.newBuilder(initEulerAngles_).mergeFrom(value).buildPartial();
          } else {
            initEulerAngles_ = value;
          }
          onChanged();
        } else {
          initEulerAnglesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public Builder clearInitEulerAngles() {
        if (initEulerAnglesBuilder_ == null) {
          initEulerAngles_ = null;
          onChanged();
        } else {
          initEulerAngles_ = null;
          initEulerAnglesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder getInitEulerAnglesBuilder() {
        
        onChanged();
        return getInitEulerAnglesFieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      public emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder getInitEulerAnglesOrBuilder() {
        if (initEulerAnglesBuilder_ != null) {
          return initEulerAnglesBuilder_.getMessageOrBuilder();
        } else {
          return initEulerAngles_ == null ?
              emu.grasscutter.net.proto.VectorOuterClass.Vector.getDefaultInstance() : initEulerAngles_;
        }
      }
      /**
       * <code>.Vector initEulerAngles = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder> 
          getInitEulerAnglesFieldBuilder() {
        if (initEulerAnglesBuilder_ == null) {
          initEulerAnglesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.VectorOuterClass.Vector, emu.grasscutter.net.proto.VectorOuterClass.Vector.Builder, emu.grasscutter.net.proto.VectorOuterClass.VectorOrBuilder>(
                  getInitEulerAngles(),
                  getParentForChildren(),
                  isClean());
          initEulerAngles_ = null;
        }
        return initEulerAnglesBuilder_;
      }

      private long guid_ ;
      /**
       * <code>uint64 guid = 8;</code>
       * @return The guid.
       */
      @java.lang.Override
      public long getGuid() {
        return guid_;
      }
      /**
       * <code>uint64 guid = 8;</code>
       * @param value The guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuid(long value) {
        
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 guid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGuid() {
        
        guid_ = 0L;
        onChanged();
        return this;
      }

      private int ownerEntityId_ ;
      /**
       * <code>uint32 ownerEntityId = 9;</code>
       * @return The ownerEntityId.
       */
      @java.lang.Override
      public int getOwnerEntityId() {
        return ownerEntityId_;
      }
      /**
       * <code>uint32 ownerEntityId = 9;</code>
       * @param value The ownerEntityId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerEntityId(int value) {
        
        ownerEntityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ownerEntityId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerEntityId() {
        
        ownerEntityId_ = 0;
        onChanged();
        return this;
      }

      private int targetEntityId_ ;
      /**
       * <code>uint32 targetEntityId = 10;</code>
       * @return The targetEntityId.
       */
      @java.lang.Override
      public int getTargetEntityId() {
        return targetEntityId_;
      }
      /**
       * <code>uint32 targetEntityId = 10;</code>
       * @param value The targetEntityId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetEntityId(int value) {
        
        targetEntityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 targetEntityId = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetEntityId() {
        
        targetEntityId_ = 0;
        onChanged();
        return this;
      }

      private boolean isAsyncLoad_ ;
      /**
       * <code>bool isAsyncLoad = 11;</code>
       * @return The isAsyncLoad.
       */
      @java.lang.Override
      public boolean getIsAsyncLoad() {
        return isAsyncLoad_;
      }
      /**
       * <code>bool isAsyncLoad = 11;</code>
       * @param value The isAsyncLoad to set.
       * @return This builder for chaining.
       */
      public Builder setIsAsyncLoad(boolean value) {
        
        isAsyncLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAsyncLoad = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAsyncLoad() {
        
        isAsyncLoad_ = false;
        onChanged();
        return this;
      }

      private int targetLockPointIndex_ ;
      /**
       * <code>uint32 targetLockPointIndex = 12;</code>
       * @return The targetLockPointIndex.
       */
      @java.lang.Override
      public int getTargetLockPointIndex() {
        return targetLockPointIndex_;
      }
      /**
       * <code>uint32 targetLockPointIndex = 12;</code>
       * @param value The targetLockPointIndex to set.
       * @return This builder for chaining.
       */
      public Builder setTargetLockPointIndex(int value) {
        
        targetLockPointIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 targetLockPointIndex = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetLockPointIndex() {
        
        targetLockPointIndex_ = 0;
        onChanged();
        return this;
      }

      private int roomId_ ;
      /**
       * <code>uint32 roomId = 13;</code>
       * @return The roomId.
       */
      @java.lang.Override
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>uint32 roomId = 13;</code>
       * @param value The roomId to set.
       * @return This builder for chaining.
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 roomId = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private int propOwnerEntityId_ ;
      /**
       * <code>uint32 propOwnerEntityId = 14;</code>
       * @return The propOwnerEntityId.
       */
      @java.lang.Override
      public int getPropOwnerEntityId() {
        return propOwnerEntityId_;
      }
      /**
       * <code>uint32 propOwnerEntityId = 14;</code>
       * @param value The propOwnerEntityId to set.
       * @return This builder for chaining.
       */
      public Builder setPropOwnerEntityId(int value) {
        
        propOwnerEntityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 propOwnerEntityId = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearPropOwnerEntityId() {
        
        propOwnerEntityId_ = 0;
        onChanged();
        return this;
      }

      private boolean sightGroupWithOwner_ ;
      /**
       * <code>bool sightGroupWithOwner = 15;</code>
       * @return The sightGroupWithOwner.
       */
      @java.lang.Override
      public boolean getSightGroupWithOwner() {
        return sightGroupWithOwner_;
      }
      /**
       * <code>bool sightGroupWithOwner = 15;</code>
       * @param value The sightGroupWithOwner to set.
       * @return This builder for chaining.
       */
      public Builder setSightGroupWithOwner(boolean value) {
        
        sightGroupWithOwner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sightGroupWithOwner = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearSightGroupWithOwner() {
        
        sightGroupWithOwner_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EvtCreateGadgetNotify)
    }

    // @@protoc_insertion_point(class_scope:EvtCreateGadgetNotify)
    private static final emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify();
    }

    public static emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EvtCreateGadgetNotify>
        PARSER = new com.google.protobuf.AbstractParser<EvtCreateGadgetNotify>() {
      @java.lang.Override
      public EvtCreateGadgetNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EvtCreateGadgetNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EvtCreateGadgetNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EvtCreateGadgetNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.EvtCreateGadgetNotifyOuterClass.EvtCreateGadgetNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EvtCreateGadgetNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EvtCreateGadgetNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033EvtCreateGadgetNotify.proto\032\021ForwardTy" +
      "pe.proto\032\014Vector.proto\"\364\002\n\025EvtCreateGadg" +
      "etNotify\022!\n\013forwardType\030\001 \001(\0162\014.ForwardT" +
      "ype\022\020\n\010entityId\030\002 \001(\r\022\020\n\010configId\030\003 \001(\r\022" +
      "\016\n\006campId\030\004 \001(\r\022\020\n\010campType\030\005 \001(\r\022\030\n\007ini" +
      "tPos\030\006 \001(\0132\007.Vector\022 \n\017initEulerAngles\030\007" +
      " \001(\0132\007.Vector\022\014\n\004guid\030\010 \001(\004\022\025\n\rownerEnti" +
      "tyId\030\t \001(\r\022\026\n\016targetEntityId\030\n \001(\r\022\023\n\013is" +
      "AsyncLoad\030\013 \001(\010\022\034\n\024targetLockPointIndex\030" +
      "\014 \001(\r\022\016\n\006roomId\030\r \001(\r\022\031\n\021propOwnerEntity" +
      "Id\030\016 \001(\r\022\033\n\023sightGroupWithOwner\030\017 \001(\010B\033\n" +
      "\031emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.ForwardTypeOuterClass.getDescriptor(),
          emu.grasscutter.net.proto.VectorOuterClass.getDescriptor(),
        });
    internal_static_EvtCreateGadgetNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EvtCreateGadgetNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EvtCreateGadgetNotify_descriptor,
        new java.lang.String[] { "ForwardType", "EntityId", "ConfigId", "CampId", "CampType", "InitPos", "InitEulerAngles", "Guid", "OwnerEntityId", "TargetEntityId", "IsAsyncLoad", "TargetLockPointIndex", "RoomId", "PropOwnerEntityId", "SightGroupWithOwner", });
    emu.grasscutter.net.proto.ForwardTypeOuterClass.getDescriptor();
    emu.grasscutter.net.proto.VectorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
