// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GadgetBornType.proto

package emu.grasscutter.net.proto;

public final class GadgetBornTypeOuterClass {
  private GadgetBornTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code GadgetBornType}
   */
  public enum GadgetBornType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GadgetBornNone = 0;</code>
     */
    GadgetBornNone(0),
    /**
     * <code>GadgetBornInAir = 1;</code>
     */
    GadgetBornInAir(1),
    /**
     * <code>GadgetBornPlayer = 2;</code>
     */
    GadgetBornPlayer(2),
    /**
     * <code>GadgetBornMonsterHit = 3;</code>
     */
    GadgetBornMonsterHit(3),
    /**
     * <code>GadgetBornMonsterDie = 4;</code>
     */
    GadgetBornMonsterDie(4),
    /**
     * <code>GadgetBornGadget = 5;</code>
     */
    GadgetBornGadget(5),
    /**
     * <code>GadgetBornGround = 6;</code>
     */
    GadgetBornGround(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GadgetBornNone = 0;</code>
     */
    public static final int GadgetBornNone_VALUE = 0;
    /**
     * <code>GadgetBornInAir = 1;</code>
     */
    public static final int GadgetBornInAir_VALUE = 1;
    /**
     * <code>GadgetBornPlayer = 2;</code>
     */
    public static final int GadgetBornPlayer_VALUE = 2;
    /**
     * <code>GadgetBornMonsterHit = 3;</code>
     */
    public static final int GadgetBornMonsterHit_VALUE = 3;
    /**
     * <code>GadgetBornMonsterDie = 4;</code>
     */
    public static final int GadgetBornMonsterDie_VALUE = 4;
    /**
     * <code>GadgetBornGadget = 5;</code>
     */
    public static final int GadgetBornGadget_VALUE = 5;
    /**
     * <code>GadgetBornGround = 6;</code>
     */
    public static final int GadgetBornGround_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GadgetBornType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GadgetBornType forNumber(int value) {
      switch (value) {
        case 0: return GadgetBornNone;
        case 1: return GadgetBornInAir;
        case 2: return GadgetBornPlayer;
        case 3: return GadgetBornMonsterHit;
        case 4: return GadgetBornMonsterDie;
        case 5: return GadgetBornGadget;
        case 6: return GadgetBornGround;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GadgetBornType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GadgetBornType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GadgetBornType>() {
            public GadgetBornType findValueByNumber(int number) {
              return GadgetBornType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.GadgetBornTypeOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final GadgetBornType[] VALUES = values();

    public static GadgetBornType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GadgetBornType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GadgetBornType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GadgetBornType.proto*\257\001\n\016GadgetBornTyp" +
      "e\022\022\n\016GadgetBornNone\020\000\022\023\n\017GadgetBornInAir" +
      "\020\001\022\024\n\020GadgetBornPlayer\020\002\022\030\n\024GadgetBornMo" +
      "nsterHit\020\003\022\030\n\024GadgetBornMonsterDie\020\004\022\024\n\020" +
      "GadgetBornGadget\020\005\022\024\n\020GadgetBornGround\020\006" +
      "B\033\n\031emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
