// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LifeStateChangeNotify.proto

package emu.grasscutter.net.proto;

public final class LifeStateChangeNotifyOuterClass {
  private LifeStateChangeNotifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LifeStateChangeNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeStateChangeNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 entityId = 1;</code>
     * @return The entityId.
     */
    int getEntityId();

    /**
     * <code>uint32 lifeState = 2;</code>
     * @return The lifeState.
     */
    int getLifeState();

    /**
     * <code>uint32 sourceEntityId = 3;</code>
     * @return The sourceEntityId.
     */
    int getSourceEntityId();

    /**
     * <code>string attackTag = 4;</code>
     * @return The attackTag.
     */
    java.lang.String getAttackTag();
    /**
     * <code>string attackTag = 4;</code>
     * @return The bytes for attackTag.
     */
    com.google.protobuf.ByteString
        getAttackTagBytes();

    /**
     * <code>.PlayerDieType dieType = 5;</code>
     * @return The enum numeric value on the wire for dieType.
     */
    int getDieTypeValue();
    /**
     * <code>.PlayerDieType dieType = 5;</code>
     * @return The dieType.
     */
    emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType getDieType();

    /**
     * <code>uint32 moveReliableSeq = 6;</code>
     * @return The moveReliableSeq.
     */
    int getMoveReliableSeq();
  }
  /**
   * Protobuf type {@code LifeStateChangeNotify}
   */
  public static final class LifeStateChangeNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeStateChangeNotify)
      LifeStateChangeNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LifeStateChangeNotify.newBuilder() to construct.
    private LifeStateChangeNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LifeStateChangeNotify() {
      attackTag_ = "";
      dieType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LifeStateChangeNotify();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LifeStateChangeNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              entityId_ = input.readUInt32();
              break;
            }
            case 16: {

              lifeState_ = input.readUInt32();
              break;
            }
            case 24: {

              sourceEntityId_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              attackTag_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              dieType_ = rawValue;
              break;
            }
            case 48: {

              moveReliableSeq_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.internal_static_LifeStateChangeNotify_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.internal_static_LifeStateChangeNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.class, emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.Builder.class);
    }

    public static final int ENTITYID_FIELD_NUMBER = 1;
    private int entityId_;
    /**
     * <code>uint32 entityId = 1;</code>
     * @return The entityId.
     */
    @java.lang.Override
    public int getEntityId() {
      return entityId_;
    }

    public static final int LIFESTATE_FIELD_NUMBER = 2;
    private int lifeState_;
    /**
     * <code>uint32 lifeState = 2;</code>
     * @return The lifeState.
     */
    @java.lang.Override
    public int getLifeState() {
      return lifeState_;
    }

    public static final int SOURCEENTITYID_FIELD_NUMBER = 3;
    private int sourceEntityId_;
    /**
     * <code>uint32 sourceEntityId = 3;</code>
     * @return The sourceEntityId.
     */
    @java.lang.Override
    public int getSourceEntityId() {
      return sourceEntityId_;
    }

    public static final int ATTACKTAG_FIELD_NUMBER = 4;
    private volatile java.lang.Object attackTag_;
    /**
     * <code>string attackTag = 4;</code>
     * @return The attackTag.
     */
    @java.lang.Override
    public java.lang.String getAttackTag() {
      java.lang.Object ref = attackTag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attackTag_ = s;
        return s;
      }
    }
    /**
     * <code>string attackTag = 4;</code>
     * @return The bytes for attackTag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttackTagBytes() {
      java.lang.Object ref = attackTag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attackTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIETYPE_FIELD_NUMBER = 5;
    private int dieType_;
    /**
     * <code>.PlayerDieType dieType = 5;</code>
     * @return The enum numeric value on the wire for dieType.
     */
    @java.lang.Override public int getDieTypeValue() {
      return dieType_;
    }
    /**
     * <code>.PlayerDieType dieType = 5;</code>
     * @return The dieType.
     */
    @java.lang.Override public emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType getDieType() {
      @SuppressWarnings("deprecation")
      emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType result = emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.valueOf(dieType_);
      return result == null ? emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.UNRECOGNIZED : result;
    }

    public static final int MOVERELIABLESEQ_FIELD_NUMBER = 6;
    private int moveReliableSeq_;
    /**
     * <code>uint32 moveReliableSeq = 6;</code>
     * @return The moveReliableSeq.
     */
    @java.lang.Override
    public int getMoveReliableSeq() {
      return moveReliableSeq_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (entityId_ != 0) {
        output.writeUInt32(1, entityId_);
      }
      if (lifeState_ != 0) {
        output.writeUInt32(2, lifeState_);
      }
      if (sourceEntityId_ != 0) {
        output.writeUInt32(3, sourceEntityId_);
      }
      if (!getAttackTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, attackTag_);
      }
      if (dieType_ != emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.PlayerDieNone.getNumber()) {
        output.writeEnum(5, dieType_);
      }
      if (moveReliableSeq_ != 0) {
        output.writeUInt32(6, moveReliableSeq_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (entityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, entityId_);
      }
      if (lifeState_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, lifeState_);
      }
      if (sourceEntityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sourceEntityId_);
      }
      if (!getAttackTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, attackTag_);
      }
      if (dieType_ != emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.PlayerDieNone.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, dieType_);
      }
      if (moveReliableSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, moveReliableSeq_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify other = (emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify) obj;

      if (getEntityId()
          != other.getEntityId()) return false;
      if (getLifeState()
          != other.getLifeState()) return false;
      if (getSourceEntityId()
          != other.getSourceEntityId()) return false;
      if (!getAttackTag()
          .equals(other.getAttackTag())) return false;
      if (dieType_ != other.dieType_) return false;
      if (getMoveReliableSeq()
          != other.getMoveReliableSeq()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getEntityId();
      hash = (37 * hash) + LIFESTATE_FIELD_NUMBER;
      hash = (53 * hash) + getLifeState();
      hash = (37 * hash) + SOURCEENTITYID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceEntityId();
      hash = (37 * hash) + ATTACKTAG_FIELD_NUMBER;
      hash = (53 * hash) + getAttackTag().hashCode();
      hash = (37 * hash) + DIETYPE_FIELD_NUMBER;
      hash = (53 * hash) + dieType_;
      hash = (37 * hash) + MOVERELIABLESEQ_FIELD_NUMBER;
      hash = (53 * hash) + getMoveReliableSeq();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LifeStateChangeNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeStateChangeNotify)
        emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.internal_static_LifeStateChangeNotify_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.internal_static_LifeStateChangeNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.class, emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        entityId_ = 0;

        lifeState_ = 0;

        sourceEntityId_ = 0;

        attackTag_ = "";

        dieType_ = 0;

        moveReliableSeq_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.internal_static_LifeStateChangeNotify_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify build() {
        emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify buildPartial() {
        emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify result = new emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify(this);
        result.entityId_ = entityId_;
        result.lifeState_ = lifeState_;
        result.sourceEntityId_ = sourceEntityId_;
        result.attackTag_ = attackTag_;
        result.dieType_ = dieType_;
        result.moveReliableSeq_ = moveReliableSeq_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify) {
          return mergeFrom((emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify other) {
        if (other == emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify.getDefaultInstance()) return this;
        if (other.getEntityId() != 0) {
          setEntityId(other.getEntityId());
        }
        if (other.getLifeState() != 0) {
          setLifeState(other.getLifeState());
        }
        if (other.getSourceEntityId() != 0) {
          setSourceEntityId(other.getSourceEntityId());
        }
        if (!other.getAttackTag().isEmpty()) {
          attackTag_ = other.attackTag_;
          onChanged();
        }
        if (other.dieType_ != 0) {
          setDieTypeValue(other.getDieTypeValue());
        }
        if (other.getMoveReliableSeq() != 0) {
          setMoveReliableSeq(other.getMoveReliableSeq());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int entityId_ ;
      /**
       * <code>uint32 entityId = 1;</code>
       * @return The entityId.
       */
      @java.lang.Override
      public int getEntityId() {
        return entityId_;
      }
      /**
       * <code>uint32 entityId = 1;</code>
       * @param value The entityId to set.
       * @return This builder for chaining.
       */
      public Builder setEntityId(int value) {
        
        entityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 entityId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEntityId() {
        
        entityId_ = 0;
        onChanged();
        return this;
      }

      private int lifeState_ ;
      /**
       * <code>uint32 lifeState = 2;</code>
       * @return The lifeState.
       */
      @java.lang.Override
      public int getLifeState() {
        return lifeState_;
      }
      /**
       * <code>uint32 lifeState = 2;</code>
       * @param value The lifeState to set.
       * @return This builder for chaining.
       */
      public Builder setLifeState(int value) {
        
        lifeState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 lifeState = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLifeState() {
        
        lifeState_ = 0;
        onChanged();
        return this;
      }

      private int sourceEntityId_ ;
      /**
       * <code>uint32 sourceEntityId = 3;</code>
       * @return The sourceEntityId.
       */
      @java.lang.Override
      public int getSourceEntityId() {
        return sourceEntityId_;
      }
      /**
       * <code>uint32 sourceEntityId = 3;</code>
       * @param value The sourceEntityId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceEntityId(int value) {
        
        sourceEntityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sourceEntityId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceEntityId() {
        
        sourceEntityId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object attackTag_ = "";
      /**
       * <code>string attackTag = 4;</code>
       * @return The attackTag.
       */
      public java.lang.String getAttackTag() {
        java.lang.Object ref = attackTag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          attackTag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string attackTag = 4;</code>
       * @return The bytes for attackTag.
       */
      public com.google.protobuf.ByteString
          getAttackTagBytes() {
        java.lang.Object ref = attackTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attackTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string attackTag = 4;</code>
       * @param value The attackTag to set.
       * @return This builder for chaining.
       */
      public Builder setAttackTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        attackTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string attackTag = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttackTag() {
        
        attackTag_ = getDefaultInstance().getAttackTag();
        onChanged();
        return this;
      }
      /**
       * <code>string attackTag = 4;</code>
       * @param value The bytes for attackTag to set.
       * @return This builder for chaining.
       */
      public Builder setAttackTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        attackTag_ = value;
        onChanged();
        return this;
      }

      private int dieType_ = 0;
      /**
       * <code>.PlayerDieType dieType = 5;</code>
       * @return The enum numeric value on the wire for dieType.
       */
      @java.lang.Override public int getDieTypeValue() {
        return dieType_;
      }
      /**
       * <code>.PlayerDieType dieType = 5;</code>
       * @param value The enum numeric value on the wire for dieType to set.
       * @return This builder for chaining.
       */
      public Builder setDieTypeValue(int value) {
        
        dieType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PlayerDieType dieType = 5;</code>
       * @return The dieType.
       */
      @java.lang.Override
      public emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType getDieType() {
        @SuppressWarnings("deprecation")
        emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType result = emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.valueOf(dieType_);
        return result == null ? emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PlayerDieType dieType = 5;</code>
       * @param value The dieType to set.
       * @return This builder for chaining.
       */
      public Builder setDieType(emu.grasscutter.net.proto.PlayerDieTypeOuterClass.PlayerDieType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dieType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PlayerDieType dieType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDieType() {
        
        dieType_ = 0;
        onChanged();
        return this;
      }

      private int moveReliableSeq_ ;
      /**
       * <code>uint32 moveReliableSeq = 6;</code>
       * @return The moveReliableSeq.
       */
      @java.lang.Override
      public int getMoveReliableSeq() {
        return moveReliableSeq_;
      }
      /**
       * <code>uint32 moveReliableSeq = 6;</code>
       * @param value The moveReliableSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMoveReliableSeq(int value) {
        
        moveReliableSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 moveReliableSeq = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoveReliableSeq() {
        
        moveReliableSeq_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeStateChangeNotify)
    }

    // @@protoc_insertion_point(class_scope:LifeStateChangeNotify)
    private static final emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify();
    }

    public static emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LifeStateChangeNotify>
        PARSER = new com.google.protobuf.AbstractParser<LifeStateChangeNotify>() {
      @java.lang.Override
      public LifeStateChangeNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LifeStateChangeNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LifeStateChangeNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LifeStateChangeNotify> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.LifeStateChangeNotifyOuterClass.LifeStateChangeNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeStateChangeNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeStateChangeNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033LifeStateChangeNotify.proto\032\023PlayerDie" +
      "Type.proto\"\241\001\n\025LifeStateChangeNotify\022\020\n\010" +
      "entityId\030\001 \001(\r\022\021\n\tlifeState\030\002 \001(\r\022\026\n\016sou" +
      "rceEntityId\030\003 \001(\r\022\021\n\tattackTag\030\004 \001(\t\022\037\n\007" +
      "dieType\030\005 \001(\0162\016.PlayerDieType\022\027\n\017moveRel" +
      "iableSeq\030\006 \001(\rB\033\n\031emu.grasscutter.net.pr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.PlayerDieTypeOuterClass.getDescriptor(),
        });
    internal_static_LifeStateChangeNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LifeStateChangeNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeStateChangeNotify_descriptor,
        new java.lang.String[] { "EntityId", "LifeState", "SourceEntityId", "AttackTag", "DieType", "MoveReliableSeq", });
    emu.grasscutter.net.proto.PlayerDieTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
