// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReliquaryUpgradeRsp.proto

package emu.grasscutter.net.proto;

public final class ReliquaryUpgradeRspOuterClass {
  private ReliquaryUpgradeRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReliquaryUpgradeRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReliquaryUpgradeRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    int getRetcode();

    /**
     * <code>uint64 targetReliquaryGuid = 2;</code>
     * @return The targetReliquaryGuid.
     */
    long getTargetReliquaryGuid();

    /**
     * <code>uint32 oldLevel = 3;</code>
     * @return The oldLevel.
     */
    int getOldLevel();

    /**
     * <code>uint32 curLevel = 4;</code>
     * @return The curLevel.
     */
    int getCurLevel();

    /**
     * <code>uint32 powerUpRate = 5;</code>
     * @return The powerUpRate.
     */
    int getPowerUpRate();

    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @return A list containing the oldAppendPropList.
     */
    java.util.List<java.lang.Integer> getOldAppendPropListList();
    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @return The count of oldAppendPropList.
     */
    int getOldAppendPropListCount();
    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @param index The index of the element to return.
     * @return The oldAppendPropList at the given index.
     */
    int getOldAppendPropList(int index);

    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @return A list containing the curAppendPropList.
     */
    java.util.List<java.lang.Integer> getCurAppendPropListList();
    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @return The count of curAppendPropList.
     */
    int getCurAppendPropListCount();
    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @param index The index of the element to return.
     * @return The curAppendPropList at the given index.
     */
    int getCurAppendPropList(int index);
  }
  /**
   * Protobuf type {@code ReliquaryUpgradeRsp}
   */
  public static final class ReliquaryUpgradeRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReliquaryUpgradeRsp)
      ReliquaryUpgradeRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReliquaryUpgradeRsp.newBuilder() to construct.
    private ReliquaryUpgradeRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReliquaryUpgradeRsp() {
      oldAppendPropList_ = emptyIntList();
      curAppendPropList_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReliquaryUpgradeRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReliquaryUpgradeRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              retcode_ = input.readInt32();
              break;
            }
            case 16: {

              targetReliquaryGuid_ = input.readUInt64();
              break;
            }
            case 24: {

              oldLevel_ = input.readUInt32();
              break;
            }
            case 32: {

              curLevel_ = input.readUInt32();
              break;
            }
            case 40: {

              powerUpRate_ = input.readUInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                oldAppendPropList_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              oldAppendPropList_.addInt(input.readUInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                oldAppendPropList_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                oldAppendPropList_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                curAppendPropList_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              curAppendPropList_.addInt(input.readUInt32());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                curAppendPropList_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                curAppendPropList_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          oldAppendPropList_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          curAppendPropList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.internal_static_ReliquaryUpgradeRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.internal_static_ReliquaryUpgradeRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.class, emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.Builder.class);
    }

    public static final int RETCODE_FIELD_NUMBER = 1;
    private int retcode_;
    /**
     * <code>int32 retcode = 1;</code>
     * @return The retcode.
     */
    @java.lang.Override
    public int getRetcode() {
      return retcode_;
    }

    public static final int TARGETRELIQUARYGUID_FIELD_NUMBER = 2;
    private long targetReliquaryGuid_;
    /**
     * <code>uint64 targetReliquaryGuid = 2;</code>
     * @return The targetReliquaryGuid.
     */
    @java.lang.Override
    public long getTargetReliquaryGuid() {
      return targetReliquaryGuid_;
    }

    public static final int OLDLEVEL_FIELD_NUMBER = 3;
    private int oldLevel_;
    /**
     * <code>uint32 oldLevel = 3;</code>
     * @return The oldLevel.
     */
    @java.lang.Override
    public int getOldLevel() {
      return oldLevel_;
    }

    public static final int CURLEVEL_FIELD_NUMBER = 4;
    private int curLevel_;
    /**
     * <code>uint32 curLevel = 4;</code>
     * @return The curLevel.
     */
    @java.lang.Override
    public int getCurLevel() {
      return curLevel_;
    }

    public static final int POWERUPRATE_FIELD_NUMBER = 5;
    private int powerUpRate_;
    /**
     * <code>uint32 powerUpRate = 5;</code>
     * @return The powerUpRate.
     */
    @java.lang.Override
    public int getPowerUpRate() {
      return powerUpRate_;
    }

    public static final int OLDAPPENDPROPLIST_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.IntList oldAppendPropList_;
    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @return A list containing the oldAppendPropList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getOldAppendPropListList() {
      return oldAppendPropList_;
    }
    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @return The count of oldAppendPropList.
     */
    public int getOldAppendPropListCount() {
      return oldAppendPropList_.size();
    }
    /**
     * <code>repeated uint32 oldAppendPropList = 6;</code>
     * @param index The index of the element to return.
     * @return The oldAppendPropList at the given index.
     */
    public int getOldAppendPropList(int index) {
      return oldAppendPropList_.getInt(index);
    }
    private int oldAppendPropListMemoizedSerializedSize = -1;

    public static final int CURAPPENDPROPLIST_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.IntList curAppendPropList_;
    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @return A list containing the curAppendPropList.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getCurAppendPropListList() {
      return curAppendPropList_;
    }
    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @return The count of curAppendPropList.
     */
    public int getCurAppendPropListCount() {
      return curAppendPropList_.size();
    }
    /**
     * <code>repeated uint32 curAppendPropList = 7;</code>
     * @param index The index of the element to return.
     * @return The curAppendPropList at the given index.
     */
    public int getCurAppendPropList(int index) {
      return curAppendPropList_.getInt(index);
    }
    private int curAppendPropListMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (retcode_ != 0) {
        output.writeInt32(1, retcode_);
      }
      if (targetReliquaryGuid_ != 0L) {
        output.writeUInt64(2, targetReliquaryGuid_);
      }
      if (oldLevel_ != 0) {
        output.writeUInt32(3, oldLevel_);
      }
      if (curLevel_ != 0) {
        output.writeUInt32(4, curLevel_);
      }
      if (powerUpRate_ != 0) {
        output.writeUInt32(5, powerUpRate_);
      }
      if (getOldAppendPropListList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(oldAppendPropListMemoizedSerializedSize);
      }
      for (int i = 0; i < oldAppendPropList_.size(); i++) {
        output.writeUInt32NoTag(oldAppendPropList_.getInt(i));
      }
      if (getCurAppendPropListList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(curAppendPropListMemoizedSerializedSize);
      }
      for (int i = 0; i < curAppendPropList_.size(); i++) {
        output.writeUInt32NoTag(curAppendPropList_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (retcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retcode_);
      }
      if (targetReliquaryGuid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, targetReliquaryGuid_);
      }
      if (oldLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, oldLevel_);
      }
      if (curLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, curLevel_);
      }
      if (powerUpRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, powerUpRate_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < oldAppendPropList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(oldAppendPropList_.getInt(i));
        }
        size += dataSize;
        if (!getOldAppendPropListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        oldAppendPropListMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < curAppendPropList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(curAppendPropList_.getInt(i));
        }
        size += dataSize;
        if (!getCurAppendPropListList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        curAppendPropListMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp other = (emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp) obj;

      if (getRetcode()
          != other.getRetcode()) return false;
      if (getTargetReliquaryGuid()
          != other.getTargetReliquaryGuid()) return false;
      if (getOldLevel()
          != other.getOldLevel()) return false;
      if (getCurLevel()
          != other.getCurLevel()) return false;
      if (getPowerUpRate()
          != other.getPowerUpRate()) return false;
      if (!getOldAppendPropListList()
          .equals(other.getOldAppendPropListList())) return false;
      if (!getCurAppendPropListList()
          .equals(other.getCurAppendPropListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetcode();
      hash = (37 * hash) + TARGETRELIQUARYGUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetReliquaryGuid());
      hash = (37 * hash) + OLDLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getOldLevel();
      hash = (37 * hash) + CURLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getCurLevel();
      hash = (37 * hash) + POWERUPRATE_FIELD_NUMBER;
      hash = (53 * hash) + getPowerUpRate();
      if (getOldAppendPropListCount() > 0) {
        hash = (37 * hash) + OLDAPPENDPROPLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOldAppendPropListList().hashCode();
      }
      if (getCurAppendPropListCount() > 0) {
        hash = (37 * hash) + CURAPPENDPROPLIST_FIELD_NUMBER;
        hash = (53 * hash) + getCurAppendPropListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReliquaryUpgradeRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReliquaryUpgradeRsp)
        emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.internal_static_ReliquaryUpgradeRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.internal_static_ReliquaryUpgradeRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.class, emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        retcode_ = 0;

        targetReliquaryGuid_ = 0L;

        oldLevel_ = 0;

        curLevel_ = 0;

        powerUpRate_ = 0;

        oldAppendPropList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        curAppendPropList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.internal_static_ReliquaryUpgradeRsp_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp build() {
        emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp buildPartial() {
        emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp result = new emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp(this);
        int from_bitField0_ = bitField0_;
        result.retcode_ = retcode_;
        result.targetReliquaryGuid_ = targetReliquaryGuid_;
        result.oldLevel_ = oldLevel_;
        result.curLevel_ = curLevel_;
        result.powerUpRate_ = powerUpRate_;
        if (((bitField0_ & 0x00000001) != 0)) {
          oldAppendPropList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.oldAppendPropList_ = oldAppendPropList_;
        if (((bitField0_ & 0x00000002) != 0)) {
          curAppendPropList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.curAppendPropList_ = curAppendPropList_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp) {
          return mergeFrom((emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp other) {
        if (other == emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp.getDefaultInstance()) return this;
        if (other.getRetcode() != 0) {
          setRetcode(other.getRetcode());
        }
        if (other.getTargetReliquaryGuid() != 0L) {
          setTargetReliquaryGuid(other.getTargetReliquaryGuid());
        }
        if (other.getOldLevel() != 0) {
          setOldLevel(other.getOldLevel());
        }
        if (other.getCurLevel() != 0) {
          setCurLevel(other.getCurLevel());
        }
        if (other.getPowerUpRate() != 0) {
          setPowerUpRate(other.getPowerUpRate());
        }
        if (!other.oldAppendPropList_.isEmpty()) {
          if (oldAppendPropList_.isEmpty()) {
            oldAppendPropList_ = other.oldAppendPropList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOldAppendPropListIsMutable();
            oldAppendPropList_.addAll(other.oldAppendPropList_);
          }
          onChanged();
        }
        if (!other.curAppendPropList_.isEmpty()) {
          if (curAppendPropList_.isEmpty()) {
            curAppendPropList_ = other.curAppendPropList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCurAppendPropListIsMutable();
            curAppendPropList_.addAll(other.curAppendPropList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retcode_ ;
      /**
       * <code>int32 retcode = 1;</code>
       * @return The retcode.
       */
      @java.lang.Override
      public int getRetcode() {
        return retcode_;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @param value The retcode to set.
       * @return This builder for chaining.
       */
      public Builder setRetcode(int value) {
        
        retcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetcode() {
        
        retcode_ = 0;
        onChanged();
        return this;
      }

      private long targetReliquaryGuid_ ;
      /**
       * <code>uint64 targetReliquaryGuid = 2;</code>
       * @return The targetReliquaryGuid.
       */
      @java.lang.Override
      public long getTargetReliquaryGuid() {
        return targetReliquaryGuid_;
      }
      /**
       * <code>uint64 targetReliquaryGuid = 2;</code>
       * @param value The targetReliquaryGuid to set.
       * @return This builder for chaining.
       */
      public Builder setTargetReliquaryGuid(long value) {
        
        targetReliquaryGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 targetReliquaryGuid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetReliquaryGuid() {
        
        targetReliquaryGuid_ = 0L;
        onChanged();
        return this;
      }

      private int oldLevel_ ;
      /**
       * <code>uint32 oldLevel = 3;</code>
       * @return The oldLevel.
       */
      @java.lang.Override
      public int getOldLevel() {
        return oldLevel_;
      }
      /**
       * <code>uint32 oldLevel = 3;</code>
       * @param value The oldLevel to set.
       * @return This builder for chaining.
       */
      public Builder setOldLevel(int value) {
        
        oldLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 oldLevel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldLevel() {
        
        oldLevel_ = 0;
        onChanged();
        return this;
      }

      private int curLevel_ ;
      /**
       * <code>uint32 curLevel = 4;</code>
       * @return The curLevel.
       */
      @java.lang.Override
      public int getCurLevel() {
        return curLevel_;
      }
      /**
       * <code>uint32 curLevel = 4;</code>
       * @param value The curLevel to set.
       * @return This builder for chaining.
       */
      public Builder setCurLevel(int value) {
        
        curLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 curLevel = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurLevel() {
        
        curLevel_ = 0;
        onChanged();
        return this;
      }

      private int powerUpRate_ ;
      /**
       * <code>uint32 powerUpRate = 5;</code>
       * @return The powerUpRate.
       */
      @java.lang.Override
      public int getPowerUpRate() {
        return powerUpRate_;
      }
      /**
       * <code>uint32 powerUpRate = 5;</code>
       * @param value The powerUpRate to set.
       * @return This builder for chaining.
       */
      public Builder setPowerUpRate(int value) {
        
        powerUpRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 powerUpRate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPowerUpRate() {
        
        powerUpRate_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList oldAppendPropList_ = emptyIntList();
      private void ensureOldAppendPropListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          oldAppendPropList_ = mutableCopy(oldAppendPropList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @return A list containing the oldAppendPropList.
       */
      public java.util.List<java.lang.Integer>
          getOldAppendPropListList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(oldAppendPropList_) : oldAppendPropList_;
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @return The count of oldAppendPropList.
       */
      public int getOldAppendPropListCount() {
        return oldAppendPropList_.size();
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @param index The index of the element to return.
       * @return The oldAppendPropList at the given index.
       */
      public int getOldAppendPropList(int index) {
        return oldAppendPropList_.getInt(index);
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @param index The index to set the value at.
       * @param value The oldAppendPropList to set.
       * @return This builder for chaining.
       */
      public Builder setOldAppendPropList(
          int index, int value) {
        ensureOldAppendPropListIsMutable();
        oldAppendPropList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @param value The oldAppendPropList to add.
       * @return This builder for chaining.
       */
      public Builder addOldAppendPropList(int value) {
        ensureOldAppendPropListIsMutable();
        oldAppendPropList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @param values The oldAppendPropList to add.
       * @return This builder for chaining.
       */
      public Builder addAllOldAppendPropList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureOldAppendPropListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, oldAppendPropList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 oldAppendPropList = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldAppendPropList() {
        oldAppendPropList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList curAppendPropList_ = emptyIntList();
      private void ensureCurAppendPropListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          curAppendPropList_ = mutableCopy(curAppendPropList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @return A list containing the curAppendPropList.
       */
      public java.util.List<java.lang.Integer>
          getCurAppendPropListList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(curAppendPropList_) : curAppendPropList_;
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @return The count of curAppendPropList.
       */
      public int getCurAppendPropListCount() {
        return curAppendPropList_.size();
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @param index The index of the element to return.
       * @return The curAppendPropList at the given index.
       */
      public int getCurAppendPropList(int index) {
        return curAppendPropList_.getInt(index);
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @param index The index to set the value at.
       * @param value The curAppendPropList to set.
       * @return This builder for chaining.
       */
      public Builder setCurAppendPropList(
          int index, int value) {
        ensureCurAppendPropListIsMutable();
        curAppendPropList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @param value The curAppendPropList to add.
       * @return This builder for chaining.
       */
      public Builder addCurAppendPropList(int value) {
        ensureCurAppendPropListIsMutable();
        curAppendPropList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @param values The curAppendPropList to add.
       * @return This builder for chaining.
       */
      public Builder addAllCurAppendPropList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCurAppendPropListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, curAppendPropList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 curAppendPropList = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurAppendPropList() {
        curAppendPropList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReliquaryUpgradeRsp)
    }

    // @@protoc_insertion_point(class_scope:ReliquaryUpgradeRsp)
    private static final emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp();
    }

    public static emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReliquaryUpgradeRsp>
        PARSER = new com.google.protobuf.AbstractParser<ReliquaryUpgradeRsp>() {
      @java.lang.Override
      public ReliquaryUpgradeRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReliquaryUpgradeRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReliquaryUpgradeRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReliquaryUpgradeRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.ReliquaryUpgradeRspOuterClass.ReliquaryUpgradeRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReliquaryUpgradeRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReliquaryUpgradeRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ReliquaryUpgradeRsp.proto\"\262\001\n\023Reliquar" +
      "yUpgradeRsp\022\017\n\007retcode\030\001 \001(\005\022\033\n\023targetRe" +
      "liquaryGuid\030\002 \001(\004\022\020\n\010oldLevel\030\003 \001(\r\022\020\n\010c" +
      "urLevel\030\004 \001(\r\022\023\n\013powerUpRate\030\005 \001(\r\022\031\n\021ol" +
      "dAppendPropList\030\006 \003(\r\022\031\n\021curAppendPropLi" +
      "st\030\007 \003(\rB\033\n\031emu.grasscutter.net.protob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReliquaryUpgradeRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReliquaryUpgradeRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReliquaryUpgradeRsp_descriptor,
        new java.lang.String[] { "Retcode", "TargetReliquaryGuid", "OldLevel", "CurLevel", "PowerUpRate", "OldAppendPropList", "CurAppendPropList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
