package emu.grasscutter.server.dispatch;

import express.http.HttpContextHandler;
import express.http.Request;
import express.http.Response;

import java.io.IOException;

/**
 * Used for processing crash dumps and logs generated by the game.
 * Logs are in JSON, and are sent to the server for logging.
 */
public final class ClientLogHandler implements HttpContextHandler {
    @Override
    public void handle(Request request, Response response) throws IOException {
        // TODO: Figure out how to dump request body and log to file.
        response.send("{\"code\":0}");
    }
}
