blank_issues_enabled: false
contact_links:
  - name: Grasscutter Discord
    url: https://discord.gg/T5vZU6UyeG
    about: If you are looking for help while using Grasscutter, please visit the Discord server.
 