package emu.grasscutter.game.dungeons.challenge.enums;

public enum ChallengeCondType {
    CHALLENGE_COND_NONE, // 00
    CHALLENGE_COND_IN_TIME, // 01
    CHALLENGE_COND_ALL_TIME, // 02
    CHALLENGE_COND_KILL_COUNT, // 03
    CHALLENGE_COND_SURVIVE, // 04
    CHALLENGE_COND_TIME_INC, // 05
    CHALLENGE_COND_KILL_FAST, // 06
    CHALLENGE_COND_DOWN_LESS, // 07
    CHALLENGE_COND_BEATEN_LESS, // 08
    CHALLENGE_COND_UNNATURAL_COUNT, // 09
    CHALLENGE_COND_FROZEN_LESS, // 10
    CHALLENGE_COND_KILL_MONSTER, // 11
    CHALLENGE_COND_TRIGGER, // 12
    CHALLENGE_COND_GUARD_HP, // 13
    CHALLENGE_COND_TIME_DEC, // 14
}
