package emu.grasscutter.game.dungeons.challenge.enums;

public enum ChallengeType {
    CHALLENGE_NONE, // 00
    CHALLENGE_KILL_COUNT, // 01
    CHALLENGE_KILL_COUNT_IN_TIME, // 02
    CHALLENGE_SURVIVE, // 03
    CHALLENGE_TIME_FLY, // 04
    CHALLENGE_KILL_COUNT_FAST, // 05
    CHALLENGE_KILL_COUNT_FROZEN_LESS, // 06
    CHALLENGE_KILL_MONSTER_IN_TIME, // 07
    CHALLENGE_TRIGGER_IN_TIME, // 08
    CHALLENGE_GUARD_HP, // 09
    CHALLENGE_KILL_COUNT_GUARD_HP, // 10
    CHALLENGE_TRIGGER_IN_TIME_FLY, // 11
    // unknown if position and time match from here on
    CHALLENGE_TRIGGER2_AVOID_TRIGGER1,
    CHALLENGE_FATHER_SUCC_IN_TIME,
    CHALLENGE_MONSTER_DAMAGE_COUNT,
    CHALLENGE_ELEMENT_REACTION_COUNT,
    CHALLENGE_FREEZE_ENEMY_IN_TIME,
    CHALLENGE_CRYSTAL_ELEMENT_REACTION_COUNT,
    CHALLENGE_SHEILD_ABSORB_DAMAGE_COUNT,
    CHALLENGE_SWIRL_ELEMENT_REACTION_COUNT,
    CHALLENGE_DIE_LESS_IN_TIME,
    CHALLENGE_TRIGGER_COUNT,
}
